"""empty message

Revision ID: 044c8be81dcb
Revises: 1dc7cc63aca2
Create Date: 2020-06-22 21:25:01.277400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '044c8be81dcb'
down_revision = '1dc7cc63aca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homeless_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_index('email', table_name='homeless__user')
    op.drop_index('username', table_name='homeless__user')
    op.drop_table('homeless__user')
    op.add_column('shelter', sa.Column('homeless_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shelter', 'homeless_user', ['homeless_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shelter', type_='foreignkey')
    op.drop_column('shelter', 'homeless_user_id')
    op.create_table('homeless__user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'homeless__user', ['username'], unique=True)
    op.create_index('email', 'homeless__user', ['email'], unique=True)
    op.drop_table('homeless_user')
    # ### end Alembic commands ###
