"""empty message

Revision ID: 1dc7cc63aca2
Revises: 4117be929159
Create Date: 2020-06-22 21:15:16.271751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc7cc63aca2'
down_revision = '4117be929159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelter_name', sa.String(length=80), nullable=True),
    sa.Column('address_1', sa.String(length=120), nullable=False),
    sa.Column('address_2', sa.String(length=120), nullable=False),
    sa.Column('beds_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shelter_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelter')
    # ### end Alembic commands ###
