"""empty message

Revision ID: 466485566ab7
Revises: 9949cc8e1232
Create Date: 2020-07-25 16:49:16.622767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466485566ab7'
down_revision = '9949cc8e1232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeless_user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'homeless_user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homeless_user', type_='unique')
    op.drop_column('homeless_user', 'phone_number')
    # ### end Alembic commands ###
