"""empty message

Revision ID: 46ef94bfc2b2
Revises: f2782b4e0094
Create Date: 2020-06-25 00:12:04.963502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ef94bfc2b2'
down_revision = 'f2782b4e0094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributor', sa.Column('date_joined', sa.DateTime(), nullable=False))
    op.add_column('homeless_user', sa.Column('date_joined', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homeless_user', 'date_joined')
    op.drop_column('contributor', 'date_joined')
    # ### end Alembic commands ###
