"""empty message

Revision ID: 53480d6f4f49
Revises: 46ef94bfc2b2
Create Date: 2020-06-25 13:57:17.303451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53480d6f4f49'
down_revision = '46ef94bfc2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('homeless_user_id', sa.Integer(), nullable=False),
    sa.Column('donated_to_homeless_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donated_to_homeless_user'], ['homeless_user.id'], ),
    sa.ForeignKeyConstraint(['homeless_user_id'], ['homeless_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposit')
    # ### end Alembic commands ###
