"""empty message

Revision ID: 7d5cd132a32c
Revises: 57050cdc74d1
Create Date: 2020-06-25 15:19:09.157513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d5cd132a32c'
down_revision = '57050cdc74d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('daily_limit', sa.Float(), nullable=True))
    op.add_column('card', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('card', sa.Column('transaction_pending', sa.Float(), nullable=True))
    op.add_column('deposit', sa.Column('contributor_user_id', sa.Integer(), nullable=False))
    op.drop_constraint('deposit_ibfk_1', 'deposit', type_='foreignkey')
    op.create_foreign_key(None, 'deposit', 'contributor', ['contributor_user_id'], ['id'])
    op.drop_column('deposit', 'donated_to_homeless_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('donated_to_homeless_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deposit', type_='foreignkey')
    op.create_foreign_key('deposit_ibfk_1', 'deposit', 'homeless_user', ['donated_to_homeless_user'], ['id'])
    op.drop_column('deposit', 'contributor_user_id')
    op.drop_column('card', 'transaction_pending')
    op.drop_column('card', 'status')
    op.drop_column('card', 'daily_limit')
    # ### end Alembic commands ###
