"""empty message

Revision ID: 8a002e025927
Revises: 466485566ab7
Create Date: 2020-07-30 15:40:13.099410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a002e025927'
down_revision = '466485566ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='homeless_user')
    op.drop_index('username', table_name='homeless_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'homeless_user', ['username'], unique=True)
    op.create_index('password', 'homeless_user', ['password'], unique=True)
    # ### end Alembic commands ###
