"""empty message

Revision ID: 9949cc8e1232
Revises: dfe90cc56727
Create Date: 2020-07-03 16:42:36.015135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9949cc8e1232'
down_revision = 'dfe90cc56727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('date_donated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposit', 'date_donated')
    # ### end Alembic commands ###
