"""empty message

Revision ID: f2782b4e0094
Revises: 044c8be81dcb
Create Date: 2020-06-24 23:18:13.541519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2782b4e0094'
down_revision = '044c8be81dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_of_contributions', sa.Integer(), nullable=True),
    sa.Column('donated_to_homeless_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donated_to_homeless_user'], ['homeless_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('homeless_user', sa.Column('currently_homless', sa.Boolean(), nullable=False))
    op.add_column('homeless_user', sa.Column('password', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'homeless_user', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homeless_user', type_='unique')
    op.drop_column('homeless_user', 'password')
    op.drop_column('homeless_user', 'currently_homless')
    op.drop_table('contributor')
    # ### end Alembic commands ###
